---
:default: &DEFAULT
  :access_key_id: 'smash low rights key'
  :secret_access_key: 'smash low rights secret'
#  :region: 'default_region'
  :regions: &REGIONS
  - 'region1'
  - 'region2'
  - 'region3'
adam:
  :access_key_id: 'AKIAIJH4SSYMEUYI2LVA'
  :secret_access_key: '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'
  :regions: &REGIONS
  - 'us-west-2'
  - 'us-west-1'
  - 'us-east-1'
